jobs:
  - job: SQLite
    strategy:
      matrix:
        Linux:
          osName: 'linux'
          imageName: 'ubuntu-16.04'
        Mac:
          osName: 'macos'
          imageName: 'macos-10.13'
        Windows:
           osName: 'Windows'
           imageName: 'vs2017-win2016'
    
    pool:
      vmImage: $(imageName)
    steps:
      - checkout: self
      - task: BatchScript@1
        inputs:
          filename: C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Enterprise\\VC\\Auxiliary\\Build\\vcvars32.bat
          modifyEnvironment: true
        displayName: 'VsDevCmd.bat'
        condition: and(succeeded(), eq(variables['osName'], 'Windows'))
      - task: Bash@3
        displayName: Build
        inputs:
          targetType: 'filePath'
          filePath: 'build_$(osName).sh'
      - publish: src
        artifact: '$(osName)Native'

  - job: SystemDataSQLite
    pool:
      vmImage: 'vs2017-win2016'
    steps:
      - bash: ./get_system_data_sqlite.sh
      - task: MSBuild@1
        inputs:
          solution: 'net/SQLite.NET.2017.MSBuild.sln'
          configuration: 'ReleaseManagedOnly'
          msbuildArguments: '/t:System_Data_SQLite_2017 /p:UseInteropDll=false /p:UseSqliteStandard=true'
      - publish: net/bin
        artifact: 'System.Data.SQLite'
          
          
