variables:
  systemDataSqliteVersion: '1.0.115.0'
  minorVersion: $[counter('minorVersion', 1)]
  nugetVersion: '$(systemDataSqliteVersion)-$(minorVersion)'

trigger:
  branches:
    include:
    - master

pr:
  branches:
    include:
    - master

stages:
  - stage: Setup
    displayName: Setup
    jobs:
      - job:
        displayName: Build Variables
        pool:
          vmImage: 'ubuntu-20.04'
        steps:
          # Set the build name properly.  The 'name' property won't recursively expand so hack here:
          - bash: echo "##vso[build.updatebuildnumber]$NUGETVERSION"
            displayName: Set Build Name

  - stage: Build
    dependsOn: []
    jobs:
    - job: SQLite
      strategy:
        matrix:
          Linux:
            osName: 'linux'
            imageName: 'ubuntu-20.04'
          Mac:
            osName: 'osx-x64'
            imageName: 'macos-11'
          MacM1:
            osName: 'osx-arm64'
            imageName: 'macos-11'
          Windows:
             osName: 'windows'
             imageName: 'windows-2019'

      pool:
        vmImage: $(imageName)
      steps:
        - checkout: self
        - task: BatchScript@1
          inputs:
            filename: C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Enterprise\\VC\\Auxiliary\\Build\\vcvars32.bat
            modifyEnvironment: true
          displayName: 'VsDevCmd.bat'
          condition: and(succeeded(), eq(variables['osName'], 'windows'))
        - task: Bash@3
          displayName: Build
          inputs:
            targetType: 'filePath'
            filePath: 'build_$(osName).sh'
        - publish: src
          artifact: '$(osName)_native'

    - job: SystemDataSQLite
      pool:
        vmImage: 'windows-2019'
      steps:
        - bash: ./get_system_data_sqlite.sh $SYSTEMDATASQLITEVERSION
        - task: MSBuild@1
          displayName: .NET 4.6.1
          inputs:
            solution: 'net/SQLite.NET.2015.MSBuild.sln'
            configuration: 'ReleaseManagedOnly'
            msbuildArguments: '/t:System_Data_SQLite_2015 /p:UseInteropDll=false /p:UseSqliteStandard=true'
        - task: DotNetCoreCLI@2
          displayName: .NET Standard 2.0
          inputs:
            command: 'build'
            projects: 'net/SQLite.NET.NetStandard20.MSBuild.sln'
            arguments: '/p:Configuration=ReleaseManagedOnly /p:UseInteropDll=false /p:UseSqliteStandard=true'

        - publish: net/bin
          artifact: 'System.Data.SQLite'

  - stage: Package
    dependsOn: Build
    jobs:
    - job: Nuget
      pool:
        vmImage: 'windows-2019'
      steps:
      - task: DownloadPipelineArtifact@2
        inputs:
          buildType: 'current'
          artifactName: windows_native
          targetPath: artifact
      - task: DownloadPipelineArtifact@2
        inputs:
          buildType: 'current'
          artifactName: osx-x64_native
          targetPath: artifact/osx-x64
          itemPattern: 'libsqlite3.dylib'
      - task: DownloadPipelineArtifact@2
        inputs:
          buildType: 'current'
          artifactName: osx-arm64_native
          targetPath: artifact/osx-arm64
          itemPattern: 'libsqlite3.dylib'
      - task: DownloadPipelineArtifact@2
        inputs:
          buildType: 'current'
          artifactName: System.Data.SQLite
          targetPath: net/bin
      - bash: |
          sed -i'' -e "s/<version>[0-9.*]\+<\/version>/<version>${NUGETVERSION}<\/version>/g" SQLite.Core.nuspec
      - task: NuGetToolInstaller@0
      - bash: |
          ls -lR
      - task: NuGetCommand@2
        inputs:
          command: 'pack'
          packagesToPack: 'SQLite.Core.nuspec'
          versioningScheme: 'off'
      - publish: $(Build.ArtifactStagingDirectory)
        artifact: NugetPackage
      - task: NuGetCommand@2
        enabled: true
        inputs:
          command: 'push'
          packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
          nuGetFeedType: 'internal'
          publishVstsFeed: '7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/f762697f-09fa-4960-89a1-64e48069bf6a'
        condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
